name: Create and publish a Docker image with security check using Snyk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-container:
    name: Build nginx container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        run: |
        ls \
        echo pwd \
        snyk monitor --file=./main.js 
       
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build Docker image
        run: docker build -t michaln28/alpine-get-started:v-${{ github.run_number }} .
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: michaln28/alpine-get-started:v-${{ github.run_number }}  
      - name: Push Docker image
        run: docker push michaln28/alpine-get-started:v-${{ github.run_number }}
      
        
        
