name: reusable-docker-workflow-called

on:
  workflow_call:
    inputs:
      new_tag:
        required: true
        type: string
    secrets:
      mydocker_user_name:
        required: true
      mydocker_password:
        required: true
      mysnyk_token:
        required: true

jobs:
  reusable-docker-workflow_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.mydocker_user_name }}
        password: ${{ secrets.mydocker_password }} 
      
    - name: Build Docker image
      run: docker build -t michaln28/alpine-get-started:${{ inputs.new_tag }} .

    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.mysnyk_token }}
      with:
        image: michaln28/alpine-get-started:${{ inputs.new_tag }}
        args: --severity-threshold=high 
          
    - name: Push Docker image
      run: docker push michaln28/alpine-get-started:${{ inputs.new_tag }}
      