  name: Create and publish a Docker image with security check using Snyk and Sonar

on:
  push:
    branches: [ "my_snyk_branch" ]
  workflow_dispatch:

jobs:

  setUp:
      runs-on: ubuntu-latest
      outputs:
        output_tag: ${{ steps.versioning.outputs.tag }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3 

        - name: Bump version and push tag
          id: versioning
          uses: anothrNick/github-tag-action@1.55.0 
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: true
            DEFAULT_BUMP: PATCH
            INITIAL_VERSION: 0.0.1
  docker:
    needs: setUp
    uses: nevosmicBynet/getting-started-with-alpine/.github/workflows/reusable-docker.yml@main
    with:
      new_tag: ${{ needs.setUp.outputs.output_tag }}
    secrets:
      mydocker_user_name: ${{ secrets.DOCKER_USER_NAME }}
      mydocker_password: ${{ secrets.DOCKER_PASSWORD }}
      mysnyk_token : ${{ secrets.SNYK_TOKEN }}

  release:
    needs: [docker,setUp]
    runs-on: ubuntu-latest
    steps:
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v6
      - name: Echo commit sha to file
        run: |
          echo ${{ github.sha }} > Release.txt
          echo ${{ github.ref }} >> Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.setUp.outputs.output_tag }}